RET-4142 : Add a null check to getHearingType
hmcts/et-hearings-api pull request #134
Opened 2023-10-20 09:01 UTC by ss-evoco

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-11-03 16:14 UTC, brendanmchugh approved these changes

2023-11-06 11:11 UTC, marcjudge requested changes

2023-11-06 11:11 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/reform/et/helper/mapping/CaseFlagsMapping.java
> +        List<PartyFlags> flags = new ArrayList<>();
Add JavaDocs

2023-11-06 11:11 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/reform/et/helper/mapping/HearingsCaseMapping.java
> +        String caseType = "BHA1-EMT";
Add JavaDocs

2023-11-06 11:11 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/reform/et/helper/mapping/HearingsPartyMapping.java
> +    public static List<PartyDetails> buildPartyObjectForHearingPayload(CaseData caseData) {
Add JavaDocs

2023-11-06 11:11 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/reform/et/service/ServiceHearingsService.java
> +    public ServiceHearingValues getServiceHearingValues(String authorization, ServiceHearingRequest request)
Add JavaDocs

2023-11-06 11:11 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/reform/et/service/ServiceLinkedCasesService.java
> +    public ListTypeItem<CaseLink> getServiceLinkedCases(String authorization, ServiceHearingRequest request)
Add JavaDocs

2023-11-06 13:33 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/reform/et/helper/mapping/HearingsDetailsMapping.java
> +    public static Integer getHearingDuration() {
No, I don't think there is. Good spot, I'll simplify

2023-11-06 14:21 UTC, marcjudge submitted a review, later dismissed

2023-11-06 14:35 UTC, marcjudge approved these changes

2023-11-06 15:45 UTC, merged